version: '3.8'
services:
  frontend:
    build:
      context: ./frontend/my-app
    container_name: nextjs_frontend
    volumes:
      - ./frontend/my-app:/app
      - /app/node_modules
    ports:
      - "5000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
    container_name: node_backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "4000:4000"
